config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'user', controllers: { sessions: 'users/sessions',
                                                  passwords: 'users/passwords',
                                                  confirmations: 'users/confirmations' },
             skip: [:registrations]
  devise_for :admins, path: 'admin', controllers: { sessions: 'admins/sessions',
                                                    passwords: 'admins/passwords',
                                                    confirmations: 'admins/confirmations' },
             skip: [:registrations]

  post 'purchase_products' => 'purchase_products#create', as: :create_purchase_products
  patch 'cart' => 'cart#update', as: :update_purchase_product
  delete 'cart' => 'cart#destroy', as: :destroy_purchase_product
  put 'cart' => 'cart#buy', as: :buy_purchase_products

  resources :cart, only: [:index]

  root 'home#index'

  devise_scope :user do
    get 'user/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'user' => 'users/registrations#update', :as => 'user_registration'
    get '/user/main' => 'users/users#index', as: :user_main
    resources :user_purchases
  end

  devise_scope :admin do
    get 'admin/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    put 'admin' => 'admins/registrations#update', :as => 'admin_registration'
    get '/admin/main' => 'admins/admins#index', as: :admin_main
    get '/admin/users' => 'admins/users#index', as: :admin_users
    post 'admin/users' => 'admins/users#create', as: :create_user
    get '/admin/users/new' => 'admins/users#new', as: :new_users
  end

  scope 'admin' do
    resources :categories, controller: 'admins/categories'
    resources :products, controller: 'admins/products' do
      member do
        patch 'archive', as: :archive
      end
      collection do
        post 'upload_product_csv'
      end
    end
    resources :purchases, controller: 'admins/purchases' do
      collection do
        post 'export_purchases'
      end
    end
    resources :statistics, controller: 'admins/statistics'
  end

  scope 'user' do
    resources :user_purchases, controller: 'users/user_purchases'
  end
  resources :products, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :products
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :products
end

app/controllers/admins/categories_controller.rb
module Admins
  class CategoriesController < ApplicationController
    before_action :set_category, only: %i[show edit update destroy]
    before_action :authenticate_admin!

    def index
      @q = Category.ransack(params[:q])
      @q.sorts = 'name asc'
      @categories = @q.result.page(params[:page]).per(4)
    end

    def show; end

    def new
      @category = Category.new
    end

    def edit; end

    def create
      @category = Category.new(category_params)
      @category.save
      redirect_to categories_path
    end

    def update
      @category.update(category_params)
      redirect_to category_path
    end

    def destroy
      if @category.products == []
        @category.destroy
        redirect_to categories_path
      else
        redirect_to categories_path, notice: 'This category contains products.'
      end
    end

    private

    def set_category
      @category = Category.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :description)
    end
  end
end

app/views/admins/categories/_category.html.erb
<div>
  <p>
    <strong>name:</strong>
    <%= category.name %>
  </p>
  <p>
    <strong>description:</strong>
    <%= category.description %>
  </p>
  <p>
    <%= link_to 'Edit this category', edit_category_path(category) %>
  </p>
  <p>
    <%= link_to 'Back to categories', categories_path %>
  </p>
</div>

app/views/admins/categories/_form.html.erb
<%= form_with(model: category) do |form| %>

  <div class='field'>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class='field'>
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>
  <div class='field'>
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/admins/categories/index.html.erb
<%= search_form_for @q do |f| %>

  <%= f.label :name_cont %>
  <%= f.search_field :name_cont %>

  <%= f.label :description_cont %>
  <%= f.search_field :description_cont %>
  <%= f.collection_select :name_eq, Category.all, :name, :name, include_blank: 'All' %>

  <%= f.submit %>
<% end %>
<% @categories.each do |category| %>
  <div>
    <h2><%= link_to "#{category.name}", category %></h2>
    <h2><%= category.description %></h2>

    <p><%= button_to 'Delete', category_path(category), method: :delete %></p>
  </div>
<% end %>
<%= paginate @categories %>

app/views/admins/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/admins/categories/show.html.erb
<%= render @category %>