config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'user', controllers: { sessions: 'users/sessions',
                                                  passwords: 'users/passwords',
                                                  confirmations: 'users/confirmations' },
             skip: [:registrations]
  devise_for :admins, path: 'admin', controllers: { sessions: 'admins/sessions',
                                                    passwords: 'admins/passwords',
                                                    confirmations: 'admins/confirmations' },
             skip: [:registrations]

  post 'purchase_products' => 'purchase_products#create', as: :create_purchase_products
  patch 'cart' => 'cart#update', as: :update_purchase_product
  delete 'cart' => 'cart#destroy', as: :destroy_purchase_product
  put 'cart' => 'cart#buy', as: :buy_purchase_products

  resources :cart, only: [:index]

  root 'home#index'

  devise_scope :user do
    get 'user/edit' => 'users/registrations#edit', :as => 'edit_user_registration'
    put 'user' => 'users/registrations#update', :as => 'user_registration'
    get '/user/main' => 'users/users#index', as: :user_main
    resources :user_purchases
  end

  devise_scope :admin do
    get 'admin/edit' => 'admins/registrations#edit', :as => 'edit_admin_registration'
    put 'admin' => 'admins/registrations#update', :as => 'admin_registration'
    get '/admin/main' => 'admins/admins#index', as: :admin_main
    get '/admin/users' => 'admins/users#index', as: :admin_users
    post 'admin/users' => 'admins/users#create', as: :create_user
    get '/admin/users/new' => 'admins/users#new', as: :new_users
  end

  scope 'admin' do
    resources :categories, controller: 'admins/categories'
    resources :products, controller: 'admins/products' do
      member do
        patch 'archive', as: :archive
      end
      collection do
        post 'upload_product_csv'
      end
    end
    resources :purchases, controller: 'admins/purchases' do
      collection do
        post 'export_purchases'
      end
    end
    resources :statistics, controller: 'admins/statistics'
  end

  scope 'user' do
    resources :user_purchases, controller: 'users/user_purchases'
  end
  resources :products, only: [:index, :show]

  namespace :api do
    namespace :v1 do
      resources :products
    end
  end
end

app/controllers/admins/purchases_controller.rb
module Admins
  class PurchasesController < ApplicationController
    before_action :authenticate_admin!

    def index
      all_purchases = Purchase.all
      @q = all_purchases.ransack(params[:q])
      @q.sorts = 'purchase_date asc'
      @query_params = query_params
      @purchases = @q.result(distinct: true).includes(:purchase_products).
                   page(params[:page]).per(4)
    end

    def export_purchases
      @purchases = if query_params.nil?
                     Purchase.all
                   else
                     Purchase.ransack(params[:q]).result
                   end
      render xlsx: 'export_purchases'
    end

    private

    def query_params
      params[:q]&.permit(:aasm_state_eq, :purchase_products_product_id_eq,
                         :purchase_date_gteq, :purchase_date_lteq,
                         :user_email_eq)
    end
  end
end

app/views/admins/purchases/index.html.erb
<%= search_form_for @q do |f| %>

  <%= f.label :purchase_date_gteq, 'Date from' %>
  <%= f.text_field :purchase_date_gteq %>

  <%= f.label :purchase_date_lteq, 'Date to' %>
  <%= f.text_field :purchase_date_lteq %>

  <%= f.label :purchase_products_product_id_eq, 'Products' %>
  <%= f.collection_select :purchase_products_product_id_eq, Product.order(:name), :id, :name, include_blank: 'All' %>

  <%= f.label :aasm_state_eq, 'Purchase state' %>
  <%= f.select :aasm_state_eq, ['pending', 'bought'], include_blank: 'All' %>

  <%= f.label :user_email_eq, 'Users' %>
  <%= f.collection_select :user_email_eq, User.order(:email), :email, :email, include_blank: 'All' %>

  <%= f.submit %>
<% end %>

<table>
  <tr>
    <th>Purchase id</th>
    <th>Purchase date</th>
    <th>Purchase status</th>
    <th>User</th>
    <th>Products</th>
    <th>Amount</th>
  </tr>
  <% @purchases.decorate.each do |purchase| %>
    <tr>
      <td><%= purchase.id %></td>
      <td><%= purchase.purchase_date %></td>
      <td><%= purchase.aasm_state %></td>
      <td><%= purchase.user_email %></td>
      <td>
        <% purchase.purchase_products.decorate.each do |purchase_product| %>
          <li>
            <%= purchase_product.product %>
          </li>
        <% end %>
      </td>
      <td>
        <% purchase.purchase_products.each do |purchase_product| %>
          <li>
            <%= purchase_product.product_amount %>
          </li>
        <% end %>
      </td>
  <% end %>
  </tr>
</table>
<%= paginate @purchases %>
<p>
  <%= button_to 'Export xls', export_purchases_purchases_path(params: { :q => @query_params }, format: 'xlsx'), method: :post %>
</p>